language: node_js
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

cache:
  directories:
    - "node_modules"

node_js:
  - "8"

env:
  - TASK=lint
  - TASK=build

script:
  - npm run $TASK

# Deploy with now onto mainnet
# Note that the Now Github integration can only deploy onto one environment at a time,
# so we use it to deploy to rinkeby and Travis to deploy to mainnet
before_deploy:
  - npm install now --no-save
  - pip3 install travis-wait-improved
deploy:
  - provider: script
    script: travis-wait-improved --timeout 30m now -A now-mainnet.json --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
      condition: $TASK = build
  - provider: script
    script: travis-wait-improved --timeout 30m now -A now-mainnet.json --target production --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
      condition: $TASK = build
